os: linux
cache:
  yarn: true
  directories:
    - ~/.cache
    - node_modules

language: node_js
node_js: 14

after_success: yarn run coverage
stages:
  - Test
  - name: Release
    if: branch = master AND commit_message !~ /(release|no-release)/

jobs:
  include:
    - stage: Release
      node_js: 14
      install: yarn install --frozen-lockfiles
      before_deploy:
        - git config user.email ${GITHUB_EMAIL:-"travis@travis-ci.org"}
        - git config user.name ${GITHUB_USER:-"Travis CI"}
        - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git checkout master
      deploy:
        skip_cleanup: true
        provider: script
        script: yarn run release
        on:
          branch: master
